spring:
  data:
    mongodb:
      port: 27017
      database: test

  cache:
    type: redis
    host:
    post:
    password:


jwt:
  secret: aGVlLWp1bi1hY3JvLTI1NmJpdC1zZWNyZXQta2V5LWZvci10ZXN0aW5nISE=
  expiration-time: 3600000
